### ISSUE TITLE
Let's Start at this point.

### ISSUE THREAD

**Issue by linan7788626** [linan7788626/Arc_Finding_with_CMU#1]
Hi @WentaoLuo ,

I just built a very naive repository on GitHub, let's discuss and update progress here.  (:

**Comment by WentaoLuo** [comment]
Sure

**Comment by WentaoLuo** [comment]
I am trying to load the SDSS PSF and SDSS galaxy image simulated using SHERA by Rachel.

**Comment by WentaoLuo** [comment]
And we should add the other three people to this job.

**Comment by linan7788626** [comment]
Maybe, not now, let's make something first, at list finish one simulated image, then we can add them in. 
BTW, you can edit the README as you will.

**Comment by WentaoLuo** [comment]
OK. I am trying to load the simulated sdss galaxy image with simply gaussian noise and a typical sdss psf image.
