### ISSUE TITLE
Modification

### ISSUE THREAD

**Issue by WentaoLuo** [linan7788626/Arc_Finding_with_CMU#14]
![figure_1](https://cloud.githubusercontent.com/assets/6350744/12922427/75d69c5a-cf1f-11e5-8818-853c621d9dff.png)
![figure_2](https://cloud.githubusercontent.com/assets/6350744/12922433/7980682c-cf1f-11e5-94b9-71a82c2af7c0.png)

I think the lens_galaxy.py contains a bug that make the pixel value very large.
Now I compared to Rachel's SHERA and get reasonable pixel values for SDSS.

**Comment by WentaoLuo** [comment]
![figure_2](https://cloud.githubusercontent.com/assets/6350744/12923052/27a85822-cf22-11e5-9376-582848d3694e.png)
![figure_3](https://cloud.githubusercontent.com/assets/6350744/12923056/28dd0a4e-cf22-11e5-8dad-08a5502896b6.png)

The top figure is the converted ACS image to SDSS image without Gaussian noise. 
The colorbar denotes the pixel value.

Guassian noise has been added to the bottom one.

The last thing to check is the unit of the magnitude from SDSS website and
make sure the magnitude is in either AB or Pogson. It seems that the schema crashed
since yesterday.

**Comment by WentaoLuo** [comment]
![figure_4](https://cloud.githubusercontent.com/assets/6350744/12923177/b60a22f8-cf22-11e5-9511-ab5ef6774104.png)

Sorry, wrong figure.

**Comment by WentaoLuo** [comment]
I did not add softbias=1000.0 and skybackground~1100.0

**Comment by WentaoLuo** [comment]
I will push these modified codes after I confirm the units.

Good luck guys!

Wentao

**Comment by linan7788626** [comment]
Hi Wentao, 

It looks reasonable now. We can talk later today. 

Thanks,
Nan

—— 
Nan Li
Postdoctoral Fellow
University of Chicago & Argonne National Lab
linan7788626.github.io

**Comment by WentaoLuo** [comment]
Sure. Let's discuss it later.

**Comment by linan7788626** [comment]
I will close issue. And we will focus on producing DES images and LSST images in the next step.
