### ISSUE TITLE
Illustris 

### ISSUE THREAD

**Issue by WentaoLuo** [linan7788626/Arc_Finding_with_CMU#21]
![shear_map_of_galaxy_galaxy_lensing](https://cloud.githubusercontent.com/assets/6350744/13304029/998f503a-db20-11e5-86af-92f2f5ef76a4.png)

Good job, Nan. The above is the shear map of a illustris halo calculated using your code.
I will work on the flexion implementation. And see if something interesting could be done.

**Comment by linan7788626** [comment]
This is just a test for lensing simulation based on Illustris simulation, I will post the lensed arc using Illustris halos later, so Wentao closed this one, thanks @WentaoLuo.
