### ISSUE TITLE
Producing images of lenses in OM10. 

### ISSUE THREAD

**Issue by linan7788626** [linan7788626/Arc_Finding_with_CMU#22]
Hi hackers, 
Let's discuss and upload results here. :-) 
@astrosonnen @byliu1990 

Science rocks!

All the best,
Nan Li

**Comment by byliu1990** [comment]
![test_rgb](https://cloud.githubusercontent.com/assets/10132464/13711195/1abe3ee8-e772-11e5-87d5-d35c16692df0.jpg)
![test_rgb1](https://cloud.githubusercontent.com/assets/10132464/13711194/1abe2cc8-e772-11e5-8292-b3407d3229d4.jpg)

**Comment by rbliu** [comment]
![test_rgb2](https://cloud.githubusercontent.com/assets/10132464/13713141/5ec643c4-e77c-11e5-935d-04693c52fcc4.jpeg)

**Comment by rbliu** [comment]
![test_new_rgb](https://cloud.githubusercontent.com/assets/10132464/13715311/c58b07e6-e788-11e5-9123-8ae57b91b85e.png)
new test rgb
