### ISSUE TITLE
idl version of lens galaxy simulation

### ISSUE THREAD

**Issue by WentaoLuo** [linan7788626/Arc_Finding_with_CMU#8]
The idl version of lens galaxy simulation is ready now.
Please feel free to curse  that idl version of code.

**Comment by WentaoLuo** [comment]
It is under the directory of images.

**Comment by WentaoLuo** [comment]
Nan,

I am thinking that if you convert the CCD value into magnitude, then the image
must look strange due to the fact that the brighter pixels has smaller mag values.
Is that the requirement of ray-tracing code?

Why don't just work on CCD pixel value?
Yes, of course I will add a function to "pixcos2pixsdss.py".

**Comment by linan7788626** [comment]
Do not worry about that, after ray-tracing, we will convert magnitude to number counting, so the final images are with “reasonable” values then. The reason we use magnitude is that it is universal for different telescopes and observations, if we use CCD pixel Values, we have to be very careful about the zero point , pixelization, exposure time, and so on.  So I prefer to use magnitude. 

—— 
Nan Li
Postdoctoral Fellow
University of Chicago & Argonne National Lab

linan7788626.github.io

**Comment by WentaoLuo** [comment]
I have update and push the new conversion function. It can:
1, convert cosmos ccd value in unit of electron/sec to ccd counts in sdss
2, sdss ccd counts to Pogson Magnitude
3, Pogson Magnitude to sdss ccd counts

**Comment by WentaoLuo** [comment]
![10times_ccd_value_sdss_noise](https://cloud.githubusercontent.com/assets/6350744/12764900/0b1c738a-c9ca-11e5-86ee-51aacb00fa07.png)
If we arbitrarily magnify the sdss ccd value converted from  cosmos ccd given a Poisson noise with SDSS variance. Then it looks like above.

**Comment by WentaoLuo** [comment]
![5times_ccd_value_sdss_noise](https://cloud.githubusercontent.com/assets/6350744/12764957/44904696-c9ca-11e5-907e-3f0219850103.png)

5 times  sdss CCD value converted from cosmos with sdss sky variance.

**Comment by WentaoLuo** [comment]
Alas,  SDSS does not have such deep observation and highly resolved CCD.

**Comment by WentaoLuo** [comment]
The zero point of ACS F814W is 26.786 and no airmass and atmospheric extinction kk, while SDSS
zeropoint is 24.148. I we set magnitude to be the same as in SDSS observation, the counts from ACS CCD have to be multiplied by a factor of 100. Problem solved guys!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by WentaoLuo** [comment]
But the question now it is getting too bright. Still something need to be corrected.

**Comment by WentaoLuo** [comment]
Sorry, SDSS zero point is in AB magnitude and zero point of F814W in AB  is 25.523.
So again, problem solved.

**Comment by WentaoLuo** [comment]
![final_figure](https://cloud.githubusercontent.com/assets/6350744/12766248/cb0ad6f4-c9d0-11e5-9469-eb9a011ec261.png)

See the updated figure. More reasonable.

**Comment by linan7788626** [comment]
good job man, I will merge them into the pipeline. thanks.

**Comment by WentaoLuo** [comment]
![noise_galaxy_softbias_sdss](https://cloud.githubusercontent.com/assets/6350744/12766303/1cfeab8e-c9d1-11e5-9e61-c9af21ae5268.png)

With color bar.

**Comment by WentaoLuo** [comment]
Thanks. We could proceed.

**Comment by WentaoLuo** [comment]
the figure above, I include softbias, noise and galaxy.

**Comment by WentaoLuo** [comment]
Nan,

I have pushed the conversion functions, please tell me
those function are enough for your next work.

Cheers,

Wentao

**Comment by linan7788626** [comment]
Thanks wentao, I will check it today, and will close this issue, if it works. :-)

**Comment by WentaoLuo** [comment]
I thought we wanted to unify all the units, so I took SDSS zeropoint but have cosmos
ccd count/second. That makes sense if we want to make the mag meaningful as far as I understand.

**Comment by WentaoLuo** [comment]
I have pushed the modified conversion functions.
Cheers,

Wentao

**Comment by linan7788626** [comment]
Thanks Wentao.

**Comment by linan7788626** [comment]
Done, I will close it.
